language: php

dist: trusty
group: deprecated-2017Q4

matrix:
  include:
  - php: nightly
    sudo: required
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - php: 7.2
    sudo: required
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - php: 7.1
    sudo: required
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - php: 7.0
    sudo: required
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - php: 5.6
    sudo: required
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - php: 5.4
    sudo: required
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - php: hhvm-3.18
    sudo: required
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - php: hhvm-3.21
    sudo: required
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - php: hhvm-3.24
    sudo: required
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - php: hhvm-nightly
    sudo: required
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    addons:
      apt:
       sources:
        - mysql-5.7-trusty
       packages:
        - mysql-server
        - mysql-client
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
      - sudo mysql_upgrade -u root
      - sudo service mysql restart
  - php: 5.3
    dist: precise
    sudo: required
    services:
      - mysql
    before_script:
      - curl -s http://getcomposer.org/installer | php
      - php composer.phar install
      - mysql -V
      - mysqldump -V
      - tests/create_users.sh
    script:
      - php -l src/Ifsnop/Mysqldump/Mysqldump.php
      - php src/Ifsnop/Mysqldump/Mysqldump.php
      - cd tests && ./test.sh
    before_install:
      - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  allow_failures:
    - php: nightly
    - php: hhvm-nightly
    - php: 5.3
